import Footer from './footer'
import Header from './header'
import Head from 'next/head'

//@ts-ignore
export default function Layout({ children }) {
  return (
    <>
        <Head>
            <title>Dual Docs</title>
            <meta name="Dualsoft official documentation" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div style={{display: 'flex'}}>
            <Header />
        </div>
        <div>
            <main>{children}</main>
            <Footer />
        </div>
    </>
  )
}